trying to check for header

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,6 +12,9 @@ jobs:
     - uses: actions/checkout@v3
     - name: Check license headers
       run: |
-        for file in $(git ls-files | grep -E '\.(js|c)$'); do
-          echo "$(cat license/LICENSE_HEADER.txt)"
+        for file in $(git ls-files | grep -E '\.(h|c)$'); do
+          if ! grep -q "$(cat license/LICENSE_HEADER.txt)" $file; then
+            echo "ERROR: Missing or incorrect license header in file $file"
+            exit 1
+          fi
         done
